### ISSUE TITLE
unexpected character after line continuation character

### ISSUE THREAD

**Issue by EvaK08** [dm-korottsev/rosreestr-xml-to-gis-converter#3]
Здравствуйте! Пытались запустить скрипт. 
Выдал ошибку "unexpected character after line continuation character" в main.py
Похоже на то, что где-то в коде лишний знак или какая-то ошибка.

Сможете помочь разобраться?

**Comment by dm-korottsev** [comment]
Решено. Проблема была в интерпретаторе.
